# Generated by Django 2.2.3 on 2019-08-03 10:11

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='正文必须为 MarkDown 格式', verbose_name='正文'),
        ),
    ]
