# Generated by Django 2.2.3 on 2019-08-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190803_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_md',
        ),
    ]
