# Generated by Django 2.2.3 on 2019-07-22 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyer', related_query_name='replyer', to=settings.AUTH_USER_MODEL, verbose_name='回复者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyto', related_query_name='replyto', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='回复博文'),
        ),
    ]
