# Generated by Django 2.2.3 on 2019-08-01 02:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_auto_20190731_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snap',
            old_name='blog',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='snap',
            unique_together={('post', 'user')},
        ),
    ]
