# Generated by Django 2.2.3 on 2019-07-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=None, verbose_name='性别')),
                ('birthday', models.DateField()),
                ('introduction', models.CharField(max_length=254, verbose_name='个人描述')),
                ('address', models.CharField(max_length=50)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
