# Generated by Django 2.2.3 on 2019-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=254, verbose_name='账号')),
                ('status', models.PositiveIntegerField(choices=[(1, '忘记密码'), (0, '邮箱注册')], verbose_name='状态')),
                ('code', models.CharField(max_length=64, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='introduction',
            field=models.CharField(default='该用户很懒，什么也没有留下...', max_length=254, verbose_name='个人描述'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=None, null=True, verbose_name='性别'),
        ),
    ]
