# Generated by Django 2.2.3 on 2019-07-23 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=254, verbose_name='账号')),
                ('status', models.PositiveIntegerField(choices=[(1, '忘记密码'), (0, '邮箱注册')], verbose_name='状态')),
                ('code', models.CharField(max_length=64, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(default=models.CharField(max_length=50, unique=True, verbose_name='用户名'), max_length=50, null=True, verbose_name='昵称')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, null=True, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('introduction', models.CharField(default='该用户很懒，什么也没有留下...', max_length=254, verbose_name='个人描述')),
                ('address', models.CharField(default='未知', max_length=50, null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
