# Generated by Django 2.2.3 on 2019-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190731_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '邮箱注册'), (1, '忘记密码')], verbose_name='状态'),
        ),
    ]
